name: CI - Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/online-art-gallery:latest
            ${{ secrets.DOCKER_USERNAME }}/online-art-gallery:${{ github.sha }}

      # Step 4: Confirmation
      - name: Echo done
        run: echo "✅ Docker image pushed successfully!"
      - name: Install kubectl on Windows
        run: |
          Invoke-WebRequest -Uri https://dl.k8s.io/release/stable.txt -OutFile version.txt
          $version = Get-Content version.txt
          Invoke-WebRequest -Uri "https://dl.k8s.io/release/$version/bin/windows/amd64/kubectl.exe" -OutFile kubectl.exe
          echo "${{ github.workspace }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append



      - name: Point to Minikube context
        run: |
          kubectl config use-context minikube

      - name: Apply manifests
        run: |
          kubectl apply -f .
      
      - name: Echo min-done
        run: echo "✅ Applied to minikube successfully!"
